#!/usr/bin/env python3
"""Build phonebook/data.js from the Excel workbook.

Usage:  python3 tools/build_phonebook.py "<path to workbook>.xlsx"

Reads the sheet "ספר טלפונים", columns A-G (header in row 1), drops empty rows
and writes a compact JS array the site loads with a plain <script> tag
(works on file:// and under the site's CSP, unlike fetch()).
"""
import json
import sys
from datetime import date

import openpyxl

SHEET = "ספר טלפונים"
COLS = 7  # A-G

if len(sys.argv) < 2:
    sys.exit("usage: build_phonebook.py <workbook.xlsx>")

wb = openpyxl.load_workbook(sys.argv[1], data_only=True, read_only=True)
ws = wb[SHEET]
rows_iter = ws.iter_rows(min_row=1, max_col=COLS, values_only=True)
header = [str(h or "").strip() for h in next(rows_iter)]

rows = []
for row in rows_iter:
    cells = ["" if v is None else str(v).strip() for v in row]
    if not any(cells):
        continue
    rows.append(cells)

out = (
    "// Generated by tools/build_phonebook.py — do not edit by hand.\n"
    f"// Source sheet: {SHEET} (columns A-G), built {date.today().isoformat()}.\n"
    "window.PHONEBOOK = "
    + json.dumps({"columns": header, "updated": date.today().isoformat(), "rows": rows},
                 ensure_ascii=False, separators=(",", ":"))
    + ";\n"
)
with open("phonebook/data.js", "w", encoding="utf-8") as f:
    f.write(out)
print(f"wrote phonebook/data.js: {len(rows)} rows, columns={header}")
